/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class yuvconvert */

#ifndef _Included_yuvconvert
#define _Included_yuvconvert
#ifdef __cplusplus
extern "C" {
#endif

//此转换的RGB模式为   byte[] =  RRRR GGGG BBBB 存储

void Yuv420ToRgbConvert(unsigned char* yuv, unsigned char* rgb, int width, int height);
void Rgb2YuvConvert(unsigned char *RGB, unsigned char *YUV , int width, int height);

void rgbTailor(unsigned char *src, int srcWidth, int srcHeight, unsigned char *dest, int destWidth, int destHeight, int startX, int startY);

void rgbCompress(unsigned char *src, int srcWidth, int srcHeight, unsigned char *dest, int destWidth, int destHeight);

void ZoomBitMap(unsigned char *pSrcImg, unsigned char *pDstImg, int nWidth, int nHeight, float fRateW,float fRateH);

void test(float,float);

#ifdef __cplusplus
}
#endif
#endif
